---
title: "Assignment 1: Introduction"
author: Andi Scroggs
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: My experience with data analytics extends to an introductory course in undergrad and some limited use during research projects. I used R thoughout my course and throughout my research. I know the basics from the course and I taught myself what I needed to know for my research. I know how to make basic plots and tables but that is the extent of my knowledge. I have never used Git before. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident that I will learn a lot from this course and that it will challenge me. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I do not feel apprehensive about taking this course nor of any of the components of this course because I know that, even if I struggle, I can get help and talk with the professors, TAs, or my classmates. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/andrea-scroggs/EDE_Fall2025

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
